apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mysql-service","namespace":"default"},"spec":{"ports":[{"port":3306,"protocol":"TCP","targetPort":3306}],"selector":{"app":"mysql-container"}}}
  creationTimestamp: "2025-11-07T18:35:38Z"
  name: mysql-service
  namespace: default
  resourceVersion: "451"
  uid: 64186b6c-8883-4403-afd3-d747450ebfc1
spec:
  clusterIP: 10.111.65.56
  clusterIPs:
  - 10.111.65.56
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-container
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
