apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-svc
spec:
  selector:
    app: redis
  ports:
  - port: 9121
    targetPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-svc
spec:
  selector:
    app: postgres
  ports:
  - port: 9187
    targetPort: 9187
