apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
  namespace: eshop-apis
  labels:
    app.kubernetes.io/name: basket-api
    app.kubernetes.io/part-of: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: basket-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: basket-api
        app.kubernetes.io/part-of: eshop
    spec:
      serviceAccountName: eshop-developer
      containers:
        - name: basket-api
          image: sma9000/basket-api:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
            - containerPort: 81
          livenessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ConnectionString
              value: redis.eshop-data
            - name: identityUrl
              value: http://identity-api
            - name: IdentityUrlExternal
              value: http://localhost:5105
            - name: EventBusConnection
              value: rabbitmq.eshop-data
            - name: UseCustomizationData
              value: "True"
            - name: AzureServiceBusEnabled
              value: "False"
            - name: CheckUpdateTime
              value: "30000"
            - name: UseLoadTest
              value: "False"
            - name: Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ
              value: Verbose
            - name: Serilog__MinimumLevel__Override__basket-api
              value: Verbose
            - name: PATH_BASE
              value: /basket-api
            - name: GRPC_PORT
              value: "81"
            - name: PORT
              value: "80"

      #     # 👇 volumeMounts MUST be inside the container
      #     volumeMounts:
      #       - name: data
      #         mountPath: /app/data

      # # 👇 volumes belong at the pod spec level (sibling to containers)
      # volumes:
      #   - name: data
      #     persistentVolumeClaim:
      #       claimName: basketdata-pvc
