apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-api
  namespace: eshop-apis
  labels:
    app.kubernetes.io/name: webhooks-api
    app.kubernetes.io/part-of: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhooks-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webhooks-api
        app.kubernetes.io/part-of: eshop
    spec:
      serviceAccountName: eshop-developer
      containers:
        - name: webhooks-api
          image: sma9000/webhooks-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 81
          livenessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ConnectionString
              value: Server=sqldata;Database=Microsoft.eShopOnContainers.Services.WebhooksDb;User Id=sa;Password=Pass@word
            - name: EventBusConnection
              value: rabbitmq
            - name: IdentityUrl
              value: http://identity-api
            - name: IdentityUrlExternal
              value: http://identity-api
---
apiVersion: v1
kind: Service
metadata:
  name: webhooks-api
  labels:
    app.kubernetes.io/name: webhooks-api
    app.kubernetes.io/part-of: eshop
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: webhooks-api
  ports:
    - name: p80
      port: 80
      targetPort: 80
