apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc
  namespace: eshop-frontend
  labels:
    app.kubernetes.io/name: webmvc
    app.kubernetes.io/part-of: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webmvc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webmvc
        app.kubernetes.io/part-of: eshop
    spec:
      serviceAccountName: eshop-frontend-deployer
      containers:
        - name: webmvc
          image: sma9000/webmvc:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
            - containerPort: 81
          livenessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ConnectionString
              value: Server=sqldata;Database=Microsoft.eShopOnContainers.Services.webmvcDb;User Id=sa;Password=Pass@word
            - name: IdentityUrl
              value: http://identity-api
            - name: IdentityUrlExternal
              value: http://localhost:5105
            - name: EventBusConnection
              value: rabbitmq
            - name: UseCustomizationData
              value: "True"
            - name: AzureServiceBusEnabled
              value: "False"
            - name: CheckUpdateTime
              value: "30000"
            - name: UseLoadTest
              value: "False"
            - name: Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ
              value: Verbose
            - name: Serilog__MinimumLevel__Override__webmvc
              value: Verbose
            - name: PATH_BASE
              value: /webmvc
            - name: GRPC_PORT
              value: "81"
            - name: PORT
              value: "80"
            - name: BasketUrl
              value: http://basket-api
            - name: CatalogUrl
              value: http://catalog-api
            - name: OrderingUrl
              value: http://ordering-api
            - name: WebhooksUrl
              value: http://webhooks-api
            - name: PaymentUrl
              value: http://payment-api
            - name: OrderingSignalrHub
              value: http://ordering-signalrhub
            - name: MarketingUrl
              value: http://webshoppingapigw.default.svc.cluster.local
            - name: LocationsUrl
              value: http://webshoppingapigw.default.svc.cluster.local
            - name: PURCHASE_URL
              valueFrom:
                configMapKeyRef:
                  name: external-links
                  key: PURCHASE_URL
            - name: ESHOP_STORAGE_CATALOG_URL
              valueFrom:
                configMapKeyRef:
                  name: external-links
                  key: ESHOP_STORAGE_CATALOG_URL
            - name: BasketUrlHC
              value: http://basket-api/hc
            - name: CatalogUrlHC
              value: http://catalog-api/hc
            - name: OrderingUrlHC
              value: http://ordering-api/hc
            - name: IdentityUrlHC
              value: http://identity-api/hc
            - name: PaymentUrlHC
              value: http://payment-api/hc
            - name: MarketingUrlHC
              value: http://webshoppingapigw.default.svc.cluster.local/hc
            - name: LocationsUrlHC
              value: http://webshoppingapigw.default.svc.cluster.local/hc
            - name: OrderingSignalrHubHC
              value: http://ordering-signalrhub/hc
