apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldata-pvc
  labels:
    app.kubernetes.io/name: mysqldata-pvc
    app.kubernetes.io/part-of: eshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldata
  labels:
    app.kubernetes.io/name: mysqldata
    app.kubernetes.io/part-of: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysqldata
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysqldata
        app.kubernetes.io/part-of: eshop
    spec:
      containers:
        - name: mysqldata
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Pass@word"
            - name: MYSQL_DATABASE
              value: "eshop"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysqldata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldata
  labels:
    app.kubernetes.io/name: mysqldata
    app.kubernetes.io/part-of: eshop
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mysqldata
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306