apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basketdata-pvc
  labels:
    app.kubernetes.io/name: basketdata-pvc
    app.kubernetes.io/part-of: eshop
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
