apiVersion: v1
kind: Service
metadata:
  name: identity-api
spec:
  type: ClusterIP
  selector:
    app: placeholder
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ordering-api
spec:
  type: ClusterIP
  selector:
    app: placeholder
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api
spec:
  type: ClusterIP
  selector:
    app: placeholder
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webhooks
spec:
  type: ClusterIP
  selector:
    app: placeholder
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ordering-signalrhub
spec:
  type: ClusterIP
  selector:
    app: placeholder
  ports:
  - port: 80
    targetPort: 80