apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels: { app: vote-postgres }
spec:
  type: ClusterIP
  selector: { app: vote-postgres }
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
