apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-static
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  volumeName: postgres-pv-hostpath
