apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: eshop-data
  labels: { app: rabbitmq }
spec:
  replicas: 1
  selector: { matchLabels: { app: rabbitmq } }
  template:
    metadata: { labels: { app: rabbitmq } }
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672   # AMQP
            - containerPort: 15672  # Mgmt UI
          env:
            - { name: RABBITMQ_DEFAULT_USER, value: guest }
            - { name: RABBITMQ_DEFAULT_PASS, value: guest }
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels: { app: rabbitmq }
spec:
  type: ClusterIP
  selector: { app: rabbitmq }
  ports:
    - { name: amqp, port: 5672, targetPort: 5672 }
    - { name: mgmt, port: 15672, targetPort: 15672 }
