apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: vote
    tier: db
spec:
  containers:
  - name: postgres
    image: postgres:15-alpine
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_DB
      value: "votes"
    ports:
    - containerPort: 5432
    # Note: No persistence here; DB data is ephemeral for this pod lab
