apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: vote
    tier: cache
spec:
  containers:
  - name: redis
    image: redis:7-alpine
    ports:
    - containerPort: 6379
    args: ["--save", "", "--appendonly", "no"]
